### ISSUE TITLE
Arduino friendly code 

### ISSUE THREAD

**Issue by mkeyno** [kanflo/esparducam#1]
hi @kanflo  and thanks for sharing the project , I'm arduino fan and I was wondering any plan to make your code in arduino  friendly environment such as arducam
BR

**Comment by kanflo** [comment]
Thanks for taking interest @mkeyno. There already is a nice port for the Arduino environment at https://github.com/ArduCAM/Arduino (both AVR and ESP8266 based). I am afraid I will not find the time to make an Arduino version of my camera demo.

**Comment by mkeyno** [comment]
thanks @kanflo for quick reply , yes I know those code and I was hopping to have your code in Arduino platform , thanks any way
